backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: pages
        label: Pages
        label_singular: Page
        file: data/pages.yml
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Path, name: path, widget: string }
