backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Page"
        name: "page"
        file: "data/pages.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Path, name: path, widget: string }
