backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Pages"
        name: "pages"
        file: "data/pages.yml"
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Path, name: path, widget: string }
