backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - label: "Navigation"
    name: "navigation"
    files:
      - label: "Navigation Item"
        name: "navigation_item"
        file: "data/navigation.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Path, name: path, widget: string }
