backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - label: Author
    name: author
    file: data/authors.yml
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Email, name: email, widget: string }