backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow

media_folder: "source/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "data/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}